"""Helper script to get Supabase connection string from dashboard.

This script guides you to get the connection string from Supabase dashboard
and helps test the connection.
"""

import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

print("=" * 60)
print("Supabase Connection String Helper")
print("=" * 60)
print()
print("Your Supabase Project:")
print("  Project Reference: drzmgazvrdoytoemjorj")
print("  Project URL: https://drzmgazvrdoytoemjorj.supabase.co")
print()
print("=" * 60)
print("How to Get Connection String:")
print("=" * 60)
print()
print("1. Go to Supabase Dashboard:")
print("   https://supabase.com/dashboard/project/drzmgazvrdoytoemjorj")
print()
print("2. Navigate to: Settings → Database")
print()
print("3. Find 'Connection string' section")
print()
print("4. Copy the connection strings:")
print()
print("   a) Connection Pooling (for application - port 6543):")
print("      - Click 'Connection pooling' tab")
print("      - Select 'Session' mode")
print("      - Copy the connection string")
print("      - Format: postgresql://postgres.[ref]:[password]@[host]:6543/postgres")
print()
print("   b) Direct connection (for migrations - port 5432):")
print("      - Click 'Connection string' tab")
print("      - Select 'URI' format")
print("      - Copy the connection string")
print("      - Format: postgresql://postgres.[ref]:[password]@[host]:5432/postgres")
print()
print("5. Update your .env file:")
print("   - Copy .env.supabase to .env: cp .env.supabase .env")
print("   - Replace [user], [password], [host], [database] with actual values")
print("   - Ensure ?sslmode=require is included")
print()
print("=" * 60)
print("Connection String Format:")
print("=" * 60)
print()
print("For Application (Connection Pooler - port 6543):")
print("  postgresql+psycopg://postgres.drzmgazvrdoytoemjorj:[PASSWORD]@")
print("  aws-0-[region].pooler.supabase.com:6543/postgres?sslmode=require")
print()
print("For Migrations (Direct Connection - port 5432):")
print("  postgresql+psycopg://postgres.drzmgazvrdoytoemjorj:[PASSWORD]@")
print("  aws-0-[region].pooler.supabase.com:5432/postgres?sslmode=require")
print()
print("Note: Replace [PASSWORD] with your actual database password")
print("      Replace [region] with your Supabase region (e.g., us-east-1)")
print()
print("=" * 60)
print("Quick Test:")
print("=" * 60)
print()
print("After updating .env, test the connection:")
print("  python -c \"from app.config import settings; print('Connection OK' if 'supabase' in settings.database_url.lower() else 'Check connection string')\"")
print()
print("Or test with the application:")
print("  uvicorn app.main:app --reload")
print("  curl http://localhost:8000/health")
print()

